language: java

env:
    global:
        - secure: "vJAui/r6nxij4T14ZAOvWQR4jQ5nmlngwrLR0KSedSjtdysvyYI8K8FOjQtaRJfLN6tfOrIZH1SYip2V5qWltw2AOGcx21I3XfK5z+AUtxh2esfPHr8VMHCbwp1hjsPS2SyHHllOeiz963wETe1dZGgpnZny2xwrR0DLsubCdmc="
        - secure: "VY0VNZ2DSroR01YjVItrHed1tdW1XDHw6J1NX2rDO3CyMYSDy0kAWiT1F/G6QfExsGaFbtLRLSIWkpKv2HhIyxr7G3vwegqvaHRDUA+PiY66EYrWcS7SWG5YqCojiucEzQwjFnXPrpvIYVgcxID3P2nfBkeqU4KD0/QSD/JLZF0="
        - secure: "OvB4Ev/6vnVhuQWzjPwnJmT4vY2LL0xdf5RVbRo5n620KyvyOvUjdeoQIQY8glkDCo97mwaheFXQZ7mclgPa+N6UKWAP0NrhGENAxf6rTYUVj+JOhqGcTKXvpSOn1Ce2sxTD3DUtVXTqQSOPzyFj5VPAQG1uERd0gUgu+5SDK3c="

# whitelist branches
branches:
    only:
        - master

before_install:
    - sudo apt-get install -y gnupg2
    - sudo apt-get install -y gnupg
    - gpg --version
    - cp secring.gpg ~/.gnupg/
    - cp pubring.gpg ~/.gnupg/
    - ls ~/.gnupg/

script:
    - mvn clean install -Dgpg.skip=true
    - mvn clean deploy --settings settings.xml

