// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transform_horoscope.proto

package com.yahoo.xpathproto.horoscope;

public final class HoroscopeSnippetProtos {
  private HoroscopeSnippetProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HoroscopeSnippetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required string sign = 2;
    /**
     * <code>required string sign = 2;</code>
     */
    boolean hasSign();
    /**
     * <code>required string sign = 2;</code>
     */
    java.lang.String getSign();
    /**
     * <code>required string sign = 2;</code>
     */
    com.google.protobuf.ByteString
        getSignBytes();

    // required string label = 3;
    /**
     * <code>required string label = 3;</code>
     */
    boolean hasLabel();
    /**
     * <code>required string label = 3;</code>
     */
    java.lang.String getLabel();
    /**
     * <code>required string label = 3;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    // required string title = 4;
    /**
     * <code>required string title = 4;</code>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 4;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 4;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // required .proto.horoscopesnippet.Summary summary = 5;
    /**
     * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
     */
    boolean hasSummary();
    /**
     * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
     */
    com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary getSummary();
    /**
     * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
     */
    com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.SummaryOrBuilder getSummaryOrBuilder();

    // required string link = 6;
    /**
     * <code>required string link = 6;</code>
     */
    boolean hasLink();
    /**
     * <code>required string link = 6;</code>
     */
    java.lang.String getLink();
    /**
     * <code>required string link = 6;</code>
     */
    com.google.protobuf.ByteString
        getLinkBytes();

    // optional string extended_link = 7;
    /**
     * <code>optional string extended_link = 7;</code>
     */
    boolean hasExtendedLink();
    /**
     * <code>optional string extended_link = 7;</code>
     */
    java.lang.String getExtendedLink();
    /**
     * <code>optional string extended_link = 7;</code>
     */
    com.google.protobuf.ByteString
        getExtendedLinkBytes();

    // optional string author = 10;
    /**
     * <code>optional string author = 10;</code>
     */
    boolean hasAuthor();
    /**
     * <code>optional string author = 10;</code>
     */
    java.lang.String getAuthor();
    /**
     * <code>optional string author = 10;</code>
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    // required string publish_date = 11;
    /**
     * <code>required string publish_date = 11;</code>
     */
    boolean hasPublishDate();
    /**
     * <code>required string publish_date = 11;</code>
     */
    java.lang.String getPublishDate();
    /**
     * <code>required string publish_date = 11;</code>
     */
    com.google.protobuf.ByteString
        getPublishDateBytes();

    // optional uint64 ts_update = 12;
    /**
     * <code>optional uint64 ts_update = 12;</code>
     */
    boolean hasTsUpdate();
    /**
     * <code>optional uint64 ts_update = 12;</code>
     */
    long getTsUpdate();
  }
  /**
   * Protobuf type {@code proto.horoscopesnippet.HoroscopeSnippet}
   */
  public static final class HoroscopeSnippet extends
      com.google.protobuf.GeneratedMessage
      implements HoroscopeSnippetOrBuilder {
    // Use HoroscopeSnippet.newBuilder() to construct.
    private HoroscopeSnippet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HoroscopeSnippet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HoroscopeSnippet defaultInstance;
    public static HoroscopeSnippet getDefaultInstance() {
      return defaultInstance;
    }

    public HoroscopeSnippet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HoroscopeSnippet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sign_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              label_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              title_ = input.readBytes();
              break;
            }
            case 42: {
              com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = summary_.toBuilder();
              }
              summary_ = input.readMessage(com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(summary_);
                summary_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              link_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              extendedLink_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000080;
              author_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000100;
              publishDate_ = input.readBytes();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000200;
              tsUpdate_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_HoroscopeSnippet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_HoroscopeSnippet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet.class, com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet.Builder.class);
    }

    public static com.google.protobuf.Parser<HoroscopeSnippet> PARSER =
        new com.google.protobuf.AbstractParser<HoroscopeSnippet>() {
      public HoroscopeSnippet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HoroscopeSnippet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HoroscopeSnippet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string sign = 2;
    public static final int SIGN_FIELD_NUMBER = 2;
    private java.lang.Object sign_;
    /**
     * <code>required string sign = 2;</code>
     */
    public boolean hasSign() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string sign = 2;</code>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sign_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sign = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string label = 3;
    public static final int LABEL_FIELD_NUMBER = 3;
    private java.lang.Object label_;
    /**
     * <code>required string label = 3;</code>
     */
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string label = 3;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          label_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string label = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string title = 4;
    public static final int TITLE_FIELD_NUMBER = 4;
    private java.lang.Object title_;
    /**
     * <code>required string title = 4;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string title = 4;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .proto.horoscopesnippet.Summary summary = 5;
    public static final int SUMMARY_FIELD_NUMBER = 5;
    private com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary summary_;
    /**
     * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
     */
    public boolean hasSummary() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
     */
    public com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary getSummary() {
      return summary_;
    }
    /**
     * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
     */
    public com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.SummaryOrBuilder getSummaryOrBuilder() {
      return summary_;
    }

    // required string link = 6;
    public static final int LINK_FIELD_NUMBER = 6;
    private java.lang.Object link_;
    /**
     * <code>required string link = 6;</code>
     */
    public boolean hasLink() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string link = 6;</code>
     */
    public java.lang.String getLink() {
      java.lang.Object ref = link_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          link_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string link = 6;</code>
     */
    public com.google.protobuf.ByteString
        getLinkBytes() {
      java.lang.Object ref = link_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string extended_link = 7;
    public static final int EXTENDED_LINK_FIELD_NUMBER = 7;
    private java.lang.Object extendedLink_;
    /**
     * <code>optional string extended_link = 7;</code>
     */
    public boolean hasExtendedLink() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string extended_link = 7;</code>
     */
    public java.lang.String getExtendedLink() {
      java.lang.Object ref = extendedLink_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          extendedLink_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string extended_link = 7;</code>
     */
    public com.google.protobuf.ByteString
        getExtendedLinkBytes() {
      java.lang.Object ref = extendedLink_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extendedLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string author = 10;
    public static final int AUTHOR_FIELD_NUMBER = 10;
    private java.lang.Object author_;
    /**
     * <code>optional string author = 10;</code>
     */
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string author = 10;</code>
     */
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          author_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string author = 10;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string publish_date = 11;
    public static final int PUBLISH_DATE_FIELD_NUMBER = 11;
    private java.lang.Object publishDate_;
    /**
     * <code>required string publish_date = 11;</code>
     */
    public boolean hasPublishDate() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string publish_date = 11;</code>
     */
    public java.lang.String getPublishDate() {
      java.lang.Object ref = publishDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          publishDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string publish_date = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPublishDateBytes() {
      java.lang.Object ref = publishDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publishDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 ts_update = 12;
    public static final int TS_UPDATE_FIELD_NUMBER = 12;
    private long tsUpdate_;
    /**
     * <code>optional uint64 ts_update = 12;</code>
     */
    public boolean hasTsUpdate() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional uint64 ts_update = 12;</code>
     */
    public long getTsUpdate() {
      return tsUpdate_;
    }

    private void initFields() {
      id_ = "";
      sign_ = "";
      label_ = "";
      title_ = "";
      summary_ = com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.getDefaultInstance();
      link_ = "";
      extendedLink_ = "";
      author_ = "";
      publishDate_ = "";
      tsUpdate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSign()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLabel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSummary()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLink()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPublishDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSummary().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSignBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLabelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTitleBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, summary_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getLinkBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getExtendedLinkBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(10, getAuthorBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(11, getPublishDateBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeUInt64(12, tsUpdate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSignBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLabelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTitleBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, summary_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getLinkBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getExtendedLinkBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getAuthorBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getPublishDateBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(12, tsUpdate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.horoscopesnippet.HoroscopeSnippet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_HoroscopeSnippet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_HoroscopeSnippet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet.class, com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet.Builder.class);
      }

      // Construct using com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSummaryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sign_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (summaryBuilder_ == null) {
          summary_ = com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.getDefaultInstance();
        } else {
          summaryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        link_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        extendedLink_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        author_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        publishDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        tsUpdate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_HoroscopeSnippet_descriptor;
      }

      public com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet getDefaultInstanceForType() {
        return com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet.getDefaultInstance();
      }

      public com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet build() {
        com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet buildPartial() {
        com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet result = new com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sign_ = sign_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.label_ = label_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (summaryBuilder_ == null) {
          result.summary_ = summary_;
        } else {
          result.summary_ = summaryBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.link_ = link_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.extendedLink_ = extendedLink_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.author_ = author_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.publishDate_ = publishDate_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.tsUpdate_ = tsUpdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet) {
          return mergeFrom((com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet other) {
        if (other == com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasSign()) {
          bitField0_ |= 0x00000002;
          sign_ = other.sign_;
          onChanged();
        }
        if (other.hasLabel()) {
          bitField0_ |= 0x00000004;
          label_ = other.label_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000008;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasSummary()) {
          mergeSummary(other.getSummary());
        }
        if (other.hasLink()) {
          bitField0_ |= 0x00000020;
          link_ = other.link_;
          onChanged();
        }
        if (other.hasExtendedLink()) {
          bitField0_ |= 0x00000040;
          extendedLink_ = other.extendedLink_;
          onChanged();
        }
        if (other.hasAuthor()) {
          bitField0_ |= 0x00000080;
          author_ = other.author_;
          onChanged();
        }
        if (other.hasPublishDate()) {
          bitField0_ |= 0x00000100;
          publishDate_ = other.publishDate_;
          onChanged();
        }
        if (other.hasTsUpdate()) {
          setTsUpdate(other.getTsUpdate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasSign()) {
          
          return false;
        }
        if (!hasLabel()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasSummary()) {
          
          return false;
        }
        if (!hasLink()) {
          
          return false;
        }
        if (!hasPublishDate()) {
          
          return false;
        }
        if (!getSummary().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.HoroscopeSnippet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required string sign = 2;
      private java.lang.Object sign_ = "";
      /**
       * <code>required string sign = 2;</code>
       */
      public boolean hasSign() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string sign = 2;</code>
       */
      public java.lang.String getSign() {
        java.lang.Object ref = sign_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sign_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sign = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSignBytes() {
        java.lang.Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sign = 2;</code>
       */
      public Builder setSign(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 2;</code>
       */
      public Builder clearSign() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 2;</code>
       */
      public Builder setSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sign_ = value;
        onChanged();
        return this;
      }

      // required string label = 3;
      private java.lang.Object label_ = "";
      /**
       * <code>required string label = 3;</code>
       */
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string label = 3;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string label = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string label = 3;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string label = 3;</code>
       */
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>required string label = 3;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        label_ = value;
        onChanged();
        return this;
      }

      // required string title = 4;
      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 4;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string title = 4;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 4;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 4;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 4;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        title_ = value;
        onChanged();
        return this;
      }

      // required .proto.horoscopesnippet.Summary summary = 5;
      private com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary summary_ = com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary, com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.Builder, com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.SummaryOrBuilder> summaryBuilder_;
      /**
       * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
       */
      public boolean hasSummary() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
       */
      public com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary getSummary() {
        if (summaryBuilder_ == null) {
          return summary_;
        } else {
          return summaryBuilder_.getMessage();
        }
      }
      /**
       * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
       */
      public Builder setSummary(com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary value) {
        if (summaryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          summary_ = value;
          onChanged();
        } else {
          summaryBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
       */
      public Builder setSummary(
          com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.Builder builderForValue) {
        if (summaryBuilder_ == null) {
          summary_ = builderForValue.build();
          onChanged();
        } else {
          summaryBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
       */
      public Builder mergeSummary(com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary value) {
        if (summaryBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              summary_ != com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.getDefaultInstance()) {
            summary_ =
              com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.newBuilder(summary_).mergeFrom(value).buildPartial();
          } else {
            summary_ = value;
          }
          onChanged();
        } else {
          summaryBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
       */
      public Builder clearSummary() {
        if (summaryBuilder_ == null) {
          summary_ = com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.getDefaultInstance();
          onChanged();
        } else {
          summaryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
       */
      public com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.Builder getSummaryBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getSummaryFieldBuilder().getBuilder();
      }
      /**
       * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
       */
      public com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.SummaryOrBuilder getSummaryOrBuilder() {
        if (summaryBuilder_ != null) {
          return summaryBuilder_.getMessageOrBuilder();
        } else {
          return summary_;
        }
      }
      /**
       * <code>required .proto.horoscopesnippet.Summary summary = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary, com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.Builder, com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.SummaryOrBuilder> 
          getSummaryFieldBuilder() {
        if (summaryBuilder_ == null) {
          summaryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary, com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.Builder, com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.SummaryOrBuilder>(
                  summary_,
                  getParentForChildren(),
                  isClean());
          summary_ = null;
        }
        return summaryBuilder_;
      }

      // required string link = 6;
      private java.lang.Object link_ = "";
      /**
       * <code>required string link = 6;</code>
       */
      public boolean hasLink() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string link = 6;</code>
       */
      public java.lang.String getLink() {
        java.lang.Object ref = link_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          link_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string link = 6;</code>
       */
      public com.google.protobuf.ByteString
          getLinkBytes() {
        java.lang.Object ref = link_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          link_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string link = 6;</code>
       */
      public Builder setLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        link_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string link = 6;</code>
       */
      public Builder clearLink() {
        bitField0_ = (bitField0_ & ~0x00000020);
        link_ = getDefaultInstance().getLink();
        onChanged();
        return this;
      }
      /**
       * <code>required string link = 6;</code>
       */
      public Builder setLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        link_ = value;
        onChanged();
        return this;
      }

      // optional string extended_link = 7;
      private java.lang.Object extendedLink_ = "";
      /**
       * <code>optional string extended_link = 7;</code>
       */
      public boolean hasExtendedLink() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string extended_link = 7;</code>
       */
      public java.lang.String getExtendedLink() {
        java.lang.Object ref = extendedLink_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          extendedLink_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string extended_link = 7;</code>
       */
      public com.google.protobuf.ByteString
          getExtendedLinkBytes() {
        java.lang.Object ref = extendedLink_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extendedLink_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string extended_link = 7;</code>
       */
      public Builder setExtendedLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        extendedLink_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string extended_link = 7;</code>
       */
      public Builder clearExtendedLink() {
        bitField0_ = (bitField0_ & ~0x00000040);
        extendedLink_ = getDefaultInstance().getExtendedLink();
        onChanged();
        return this;
      }
      /**
       * <code>optional string extended_link = 7;</code>
       */
      public Builder setExtendedLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        extendedLink_ = value;
        onChanged();
        return this;
      }

      // optional string author = 10;
      private java.lang.Object author_ = "";
      /**
       * <code>optional string author = 10;</code>
       */
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public Builder setAuthor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        author_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public Builder clearAuthor() {
        bitField0_ = (bitField0_ & ~0x00000080);
        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        author_ = value;
        onChanged();
        return this;
      }

      // required string publish_date = 11;
      private java.lang.Object publishDate_ = "";
      /**
       * <code>required string publish_date = 11;</code>
       */
      public boolean hasPublishDate() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string publish_date = 11;</code>
       */
      public java.lang.String getPublishDate() {
        java.lang.Object ref = publishDate_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          publishDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string publish_date = 11;</code>
       */
      public com.google.protobuf.ByteString
          getPublishDateBytes() {
        java.lang.Object ref = publishDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          publishDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string publish_date = 11;</code>
       */
      public Builder setPublishDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        publishDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string publish_date = 11;</code>
       */
      public Builder clearPublishDate() {
        bitField0_ = (bitField0_ & ~0x00000100);
        publishDate_ = getDefaultInstance().getPublishDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string publish_date = 11;</code>
       */
      public Builder setPublishDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        publishDate_ = value;
        onChanged();
        return this;
      }

      // optional uint64 ts_update = 12;
      private long tsUpdate_ ;
      /**
       * <code>optional uint64 ts_update = 12;</code>
       */
      public boolean hasTsUpdate() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional uint64 ts_update = 12;</code>
       */
      public long getTsUpdate() {
        return tsUpdate_;
      }
      /**
       * <code>optional uint64 ts_update = 12;</code>
       */
      public Builder setTsUpdate(long value) {
        bitField0_ |= 0x00000200;
        tsUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ts_update = 12;</code>
       */
      public Builder clearTsUpdate() {
        bitField0_ = (bitField0_ & ~0x00000200);
        tsUpdate_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.horoscopesnippet.HoroscopeSnippet)
    }

    static {
      defaultInstance = new HoroscopeSnippet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.horoscopesnippet.HoroscopeSnippet)
  }

  public interface SummaryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string text = 1;
    /**
     * <code>required string text = 1;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code proto.horoscopesnippet.Summary}
   */
  public static final class Summary extends
      com.google.protobuf.GeneratedMessage
      implements SummaryOrBuilder {
    // Use Summary.newBuilder() to construct.
    private Summary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Summary(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Summary defaultInstance;
    public static Summary getDefaultInstance() {
      return defaultInstance;
    }

    public Summary getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Summary(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              text_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_Summary_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_Summary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.class, com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.Builder.class);
    }

    public static com.google.protobuf.Parser<Summary> PARSER =
        new com.google.protobuf.AbstractParser<Summary>() {
      public Summary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Summary(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Summary> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    /**
     * <code>required string text = 1;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.horoscopesnippet.Summary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.SummaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_Summary_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_Summary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.class, com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.Builder.class);
      }

      // Construct using com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_Summary_descriptor;
      }

      public com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary getDefaultInstanceForType() {
        return com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.getDefaultInstance();
      }

      public com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary build() {
        com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary buildPartial() {
        com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary result = new com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary) {
          return mergeFrom((com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary other) {
        if (other == com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary.getDefaultInstance()) return this;
        if (other.hasText()) {
          bitField0_ |= 0x00000001;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yahoo.xpathproto.horoscope.HoroscopeSnippetProtos.Summary) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string text = 1;
      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.horoscopesnippet.Summary)
    }

    static {
      defaultInstance = new Summary(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.horoscopesnippet.Summary)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_horoscopesnippet_HoroscopeSnippet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_horoscopesnippet_HoroscopeSnippet_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_horoscopesnippet_Summary_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_horoscopesnippet_Summary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031transform_horoscope.proto\022\026proto.horos" +
      "copesnippet\"\332\001\n\020HoroscopeSnippet\022\n\n\002id\030\001" +
      " \002(\t\022\014\n\004sign\030\002 \002(\t\022\r\n\005label\030\003 \002(\t\022\r\n\005tit" +
      "le\030\004 \002(\t\0220\n\007summary\030\005 \002(\0132\037.proto.horosc" +
      "opesnippet.Summary\022\014\n\004link\030\006 \002(\t\022\025\n\rexte" +
      "nded_link\030\007 \001(\t\022\016\n\006author\030\n \001(\t\022\024\n\014publi" +
      "sh_date\030\013 \002(\t\022\021\n\tts_update\030\014 \001(\004\"\027\n\007Summ" +
      "ary\022\014\n\004text\030\001 \002(\tB8\n\036com.yahoo.xpathprot" +
      "o.horoscopeB\026HoroscopeSnippetProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_horoscopesnippet_HoroscopeSnippet_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_horoscopesnippet_HoroscopeSnippet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_horoscopesnippet_HoroscopeSnippet_descriptor,
              new java.lang.String[] { "Id", "Sign", "Label", "Title", "Summary", "Link", "ExtendedLink", "Author", "PublishDate", "TsUpdate", });
          internal_static_proto_horoscopesnippet_Summary_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_horoscopesnippet_Summary_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_horoscopesnippet_Summary_descriptor,
              new java.lang.String[] { "Text", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
